name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'OfflineAppTest', destination: 'platform=iOS Simulator,OS=14.3,name=iPhone SE (2nd generation)' }
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: build and test
      run: xcodebuild -scheme 'OfflineAppTest' -workspace 'OfflineAppTest.xcworkspace' -destination 'platform=iOS Simulator,OS=14.3,name=iPhone SE (2nd generation)' -showBuildTimingSummary
